Models/Entity/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Website.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class productEntities : DbContext
    {
        public productEntities()
            : base("name=productEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
    }
}

Models/Entity/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\umutd\Desktop\Ecommerce_Website\Ecommerce_Website\Models\Entity\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Entity/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


Models/Entity/Tbl_Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Website.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        public int ProductCode { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductImage { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ecommerce_Website.Models.Entity;
namespace Ecommerce_Website.Controllers


{
    public class CustomerController : Controller
    {

        // GET: Customer
        productEntities db = new productEntities();
        
        public ActionResult Index(string p)
        {
            var values = from v in db.Tbl_Product select v;
            if (!string.IsNullOrEmpty(p))
            {
                values = values.Where(m => m.ProductTitle.Contains(p) || m.ProductDescription.Contains(p));
            }
            return View(values.ToList());
            
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ecommerce_Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ecommerce_Website.Models.Entity;

namespace Ecommerce_Website.Controllers
{
    public class ManagementController : Controller
    {

        // GET: Management
        
        productEntities db = new productEntities();
        public ActionResult Index()
        {
            var values = db.Tbl_Product.ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult Add_New_Product()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add_New_Product(Tbl_Product p1)
        {

            db.Tbl_Product.Add(p1);
            db.SaveChanges();
            ViewBag.Message = "Product added successfully";
            return View();
        }
        public ActionResult DELETE(int id)
        {
            var product = db.Tbl_Product.Find(id);
            db.Tbl_Product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ProductGet(int id)
        {
            var product = db.Tbl_Product.Find(id);
            return View("ProductGet", product);
        }
        public ActionResult Update(Tbl_Product p1)
        {
            var product = db.Tbl_Product.Find(p1.ProductCode);
            product.ProductTitle = p1.ProductTitle;
            product.ProductDescription = p1.ProductDescription;
            product.Stock = p1.Stock;
            product.ProductPrice = p1.ProductPrice;
            product.ProductImage = p1.ProductImage;
            db.SaveChanges();
            return RedirectToAction("Index");
        }




    }
}

Views/Customer/Index.cshtml
@using Ecommerce_Website.Models.Entity
@model List<Tbl_Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Customer", FormMethod.Get))
{
    <p>
        Search Product: @Html.TextBox("p")
        <input type="submit" value="Search">
    </p>
}


<!--
<p>
    @using (Html.BeginForm("Index","Customer",FormMethod.Get))
    {
    <b>Search By:</b> @Html.RadioButton("searchBy", "ProductTitle",true) <text>Name</text>
    @Html.RadioButton("searchBy", "ProductDescription") <text>Description</text><br/>
    @Html.TextBox("search") <input type="submit" value="Search" />
    }
</p>
-->
<table class="table table-bordered">
    <tr>
        <th>Product Code</th>
        <th>Product Name</th>
        <th>Description</th>
        <th>Stock</th>
        <th>Price</th>
        <th>Image</th>
    </tr>
    <tbody>
        @foreach (var prdct in Model)
        {
            <tr>
                <td>@prdct.ProductCode</td>
                <td>@prdct.ProductTitle</td>
                <td>@prdct.ProductDescription</td>
                <td>@prdct.Stock</td>
                <td>@prdct.ProductPrice</td>
                <td><img src=@prdct.ProductImage height="65" width="65"></td>
            </tr>
        }

    </tbody>
</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Management/Add_New_Product.cshtml

@{
    ViewBag.Title = "Add_New_Product";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Product Name</label>
        <input type="text" class="form-control" name="ProductTitle" />
    </div>
    <div>
        <label>Product Description</label>
        <input type="text" class="form-control" name="ProductDescription" />
    </div>
    <div>
        <label>Stock</label>
        <input type="text" class="form-control" name="Stock" />
    </div>
    <div>
        <label>Price</label>
        <input type="text" class="form-control" name="ProductPrice" />
    </div>
    <div>
        <label>Image(Please enter URL of product)</label>
        <input type="text" class="form-control" name="ProductImage" />
    </div>

    <div style=" margin-top:15px">
        <button class="btn btn-info">Add Product</button>
    </div>
    <div>
        @if(ViewBag.Message!=null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.Message")
                }
            </script>
        }
    </div>
</form>


Views/Management/Index.cshtml
@using Ecommerce_Website.Models.Entity
@model List<Tbl_Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th>Product Code</th>
        <th>Product Name</th>
        <th>Description</th>
        <th>Stock</th>
        <th>Price</th>
        <th>Image</th>
        <th>DELETE</th>
        <th>EDIT</th>
        <th><a href="/Management/ADD_NEW_PRODUCT" class="btn btn-primary">ADD NEW PRODUCT</a></th>
    </tr>
    <tbody>
        @foreach (var prdct in Model)
        {
        <tr>
            <td>@prdct.ProductCode</td>
            <td>@prdct.ProductTitle</td>
            <td>@prdct.ProductDescription</td>
            <td>@prdct.Stock</td>
            <td>@prdct.ProductPrice</td>
            <td><img src=@prdct.ProductImage height="65" width="65"></td>

            <td><a href="/Management/DELETE/@prdct.ProductCode" class="btn btn-danger">DEL</a></td>
            <td><a href="/Management/ProductGet/@prdct.ProductCode" class="btn btn-success">EDIT</a></td>
        </tr>
        }

    </tbody>
</table>

Views/Management/ProductGet.cshtml
@model Ecommerce_Website.Models.Entity.Tbl_Product

@{
    ViewBag.Title = "ProductGet";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Update", "Management", FormMethod.Post,new { enctype="multipart/form-data"}))
{
<div class="form-group">
    @Html.LabelFor(m => m.ProductCode)
    @Html.TextBoxFor(m => m.ProductCode, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ProductTitle)
    @Html.TextBoxFor(m => m.ProductTitle, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ProductDescription)
    @Html.TextBoxFor(m => m.ProductDescription, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Stock)
    @Html.TextBoxFor(m => m.Stock, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ProductPrice)
    @Html.TextBoxFor(m => m.ProductPrice, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.ProductImage)
    @Html.TextBoxFor(m => m.ProductImage, new { @class = "form-control" })

</div>
    <div>
        <button class="btn btn-warning">Update Product</button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_MainLayout.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ecommerce</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">EcommerceWebsite</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="/Management/Index/">Management</a></li>
                <li><a href="/Customer/Index/">Customer</a></li>
                <!--           <li><a href="/CustomerList/Index/">Customer List</a></li>    -->

            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>
